### ISSUE TITLE
Generated '.npy' only has one point not equal to 0 for each keypoint?

### ISSUE THREAD

**Issue by luowy1001** [tengteng95/Pose-Transfer#10]
Firstly, thanks for your great work!
I followed your introduction `python tool/generate_pose_map_fashion.py` to generate some '.npy'. After completion,  I check these '.npy' files, I fund that there is only one point not equals to 0 for each keypoint (it equals to 0).  But I think it should be a Gauss map. Because you employ the function `cords_to_map`.
Where it is wrong?
THANKS!
@tengteng95

**Comment by luowy1001** [comment]
I think you set the type of data as 'uint8' in this line:
`result = np.zeros(img_size + cords.shape[0:1], dtype='uint8')`
Do you want to use Gostu or a single point?

**Comment by tengteng95** [comment]
Yes, you're right. For the Deep Fashion dataset, we set the type of data as 'uint8' to **save the disk space**.  For data type 'float32', it would occupy more than 160GB due to the high resolution of Deep Fashion. And we empirically find that these two representations for key points will not bring an obvious difference in performance.

**Comment by luowy1001** [comment]
Thanks！
