### ISSUE TITLE
How to reduce noises in generated images?

### ISSUE THREAD

**Issue by abcyzj** [tengteng95/Pose-Transfer#15]
I trained a model on my computer using your code, and find that images generated by my model have more noises than those generated by your pre-trained model. I want to know if there is any trick during initializing or training? Thanks.

Here are some examples:

My model:

![fashionMENJackets_Vestsid0000065304_4full jpg___fashionMENJackets_Vestsid0000065304_3back jpg_vis](https://user-images.githubusercontent.com/26025487/59089440-ad4c1b80-893c-11e9-8551-ac2a76481f2e.jpg)

Pre-trained model:
![fashionMENJackets_Vestsid0000065304_4full jpg___fashionMENJackets_Vestsid0000065304_3back jpg_vis](https://user-images.githubusercontent.com/26025487/59089497-d8cf0600-893c-11e9-84b2-c654c5696189.jpg)

My model:
![fashionMENJackets_Vestsid0000065304_4full jpg___fashionMENJackets_Vestsid0000065304_1front jpg_vis](https://user-images.githubusercontent.com/26025487/59089582-1cc20b00-893d-11e9-8a02-b37dc86bf94a.jpg)

Pre-trained model:
![fashionMENJackets_Vestsid0000065304_4full jpg___fashionMENJackets_Vestsid0000065304_1front jpg_vis](https://user-images.githubusercontent.com/26025487/59089623-31060800-893d-11e9-953a-2fb6ca8c54aa.jpg)

I trained my model using all the hyper-parameters described in README for 700 epochs.

**Comment by tengteng95** [comment]
Hi! We do not utilize extra tricks for training.  The minor differences between the two model are quite normal since different initialed weights might lead to different local optimal solutions when training. According to my experience, we can get a relatively good result after 500 epochs. Hence, we also recommend you to test the earlier checkpoints, which may lead to better results.
