### ISSUE TITLE
Pre-trained Model (PATN_Fine)

### ISSUE THREAD

**Issue by DaichiMorimoto** [tengteng95/Pose-Transfer#78]
Thank you for your great code and the project is very interesting.
I used both PATN and PATN_Fine, but I couldn't find pre-trained model of PATN_Fine.

How can we get the pre-trained model or could you provide it?

**Comment by jessemelpolio** [comment]
Hi, thanks for your positive comments. The thing is we cannot get access to our server due to the impact of the COVID-19 pandemic. We will release the model when we have access. Please stay tuned. If you cannot wait, you could also try to train it yourself. If you have already walked through the steps to train PATN, it won't be a hard problem to train the PATN_Fine model except that it might take longer training time.

**Comment by jessemelpolio** [comment]
Hi @DaichiMorimoto , the pre-trained model for PATN_Fine is now at [this link](https://drive.google.com/drive/folders/1d1GdjnityUZKSSwf_bhcJ2Lc-qsB2w2Y?usp=sharing) (for pytorch 0.3.1, branch PATN_Fine).
