### ISSUE TITLE
Question about generalizing to other domian.

### ISSUE THREAD

**Issue by ChrisTrueman00** [tengteng95/Pose-Transfer#90]
Excellent work!I've read your paper and noticed that you said your method can be potentially adapted to generate other non-rigid objects.I have two questions for you:
- Did you test on datasets from other domains, such as animal pose transfer?
- If I want to adopt your methods on datasets from other domians such as bird pose transfer, what should I do and can I achieve the same performance due to the less keypoints(less than 8)?

Thanks.

**Comment by jessemelpolio** [comment]
Hi @ChrisTrueman00 , thanks for your interest.

1. We have tested on other domains like face rotation using face landmarks as pose joints. We observed that despite the areas out of faces, the model is able to do a plausible rotation in the main portion of faces. I think after some modifications, such as some specifically designed task-related loss functions, the model is able to do transfer on other related domains. 
2. I do not think fewer keypoints could be an issue. From my experience, I think you should check if the keypoints are placed very closely to each other, with my concern that there could be a problem for the network to split these points. Backgrounds could also be an issue, because we actually made an assumption that our main task has nothing to do with background generation while in fact it could be an issue. Besides, try to design some specific loss functions for your task if you want better performance.

**Comment by ChrisTrueman00** [comment]
Thanks for your reply. I got that!
